version: '3.8'
x-app-common: &common-variables
  POSTGRES_NAME: wsmc
  POSTGRES_USER: user
  POSTGRES_PASSWORD: 741963
  FIELD_ENCRYPTION_KEY: ${FIELD_ENCRYPTION_KEY} # Precalculated key
  WEBDRIVER_URL: 'http://webdriver:4444'
  SELENIUM_DRIVER: 'chrome'
  NOMINATIM_USER_AGENT: 'wsmc_test_app'
  CELERY_BROKER_URL: 'redis://redis:6379/'
  DEBUG: '1'
x-app-telegram: &telegram-vars
  TELEGRAM_API_ID: ${TELEGRAM_API_ID}
  TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
  TELEGRAM_PHONE: ${TELEGRAM_PHONE}

services:
  app:
    image: indiwine/wsmc:latest
    hostname: 'app'
    ports:
      - "8000:8000"
    environment:
      <<: *common-variables
      <<: *telegram-vars
    volumes:
      - tdlib:/tmp/.tdlib_files/
    depends_on:
      - postgres
      - webdriver
      - redis
      - celery
  celery:
    image: indiwine/wsmc:latest
    hostname: 'celery'
    command: celery -A wsmc worker
    environment: *common-variables
    depends_on:
      - redis
      - postgres
      - webdriver
  redis:
    image: redis:7-alpine
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "741963"
      POSTGRES_DB: "wsmc"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  webdriver:
    image: selenium/standalone-chrome:105.0
    shm_size: "2g"
    environment:
      SE_VNC_NO_PASSWORD: 1
    ports:
      - "7900:7900"
      - "5900:5900"
volumes:
  postgresql:
  tdlib: