version: '3.8'
services:
  app:
    build: './app'
    volumes:
      - './app:/app'
      - './app/storage:/app/storage'
  redis:
    ports:
      - "6379:6379"
  celery:
    build: './app'
#    command: celery -A wsmc worker -P solo
    volumes:
      - './app:/app'
      - './app/storage:/app/storage'
  chrome:
    ports:
      - "7900:7900"
    deploy:
      replicas: 1
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data