version: '3.8'
x-app-common: &common-variables
  POSTGRES_NAME: wsmc
  POSTGRES_USER: user
  POSTGRES_PASSWORD: 741963
  FIELD_ENCRYPTION_KEY: ${FIELD_ENCRYPTION_KEY} # Precalculated key
  WEBDRIVER_URL: 'http://webdriver:4444'
  SELENIUM_DRIVER: 'chrome'
  NOMINATIM_USER_AGENT: 'wsmc_test_app'
  CELERY_BROKER_URL: 'redis://redis:6379/'
  WSMC_LOAD_AI: ${WSMC_LOAD_AI}
  TF_CPP_MIN_LOG_LEVEL: 2
x-app-telegram: &telegram-vars
  TELEGRAM_API_ID: ${TELEGRAM_API_ID}
  TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
x-selenium-nodes: &selenium-nodes
  SE_EVENT_BUS_HOST: 'webdriver'
  SE_EVENT_BUS_PUBLISH_PORT: 4442
  SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  SE_VNC_NO_PASSWORD: 1

services:
  app:
    image: indiwine/wsmc:latest
    hostname: 'app'
    ports:
      - "8000:8000"
    environment:
      <<: [ *common-variables, *telegram-vars ]
    volumes:
      - tdlib:/tmp/.tdlib_files/
      - wsmc-storage:/app/storage
    depends_on:
      - postgres
      - webdriver
      - redis
      - celery
  celery:
    image: indiwine/wsmc:latest
    hostname: 'celery'
    command: celery -A wsmc worker --concurrency=3
    volumes:
      - wsmc-storage:/app/storage
    environment:
      <<: *common-variables
    depends_on:
      - redis
      - postgres
      - webdriver
  redis:
    image: redis:7-alpine
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "741963"
      POSTGRES_DB: "wsmc"
    volumes:
      - postgresql:/var/lib/postgresql/data

  chrome-01:
    image: selenium/node-chrome:112.0
    shm_size: "2g"
    depends_on:
      - webdriver
    environment:
      <<: *selenium-nodes
    ports:
      - "7900:7900"

  chrome-02:
    image: selenium/node-chrome:112.0
    shm_size: "2g"
    depends_on:
      - webdriver
    environment:
      <<: *selenium-nodes
    ports:
      - "7901:7900"

  chrome-03:
    image: selenium/node-chrome:112.0
    shm_size: "2g"
    depends_on:
      - webdriver
    environment:
      <<: *selenium-nodes
    ports:
      - "7902:7900"

  #  chrome-04:
  #    image: selenium/node-chrome:112.0
  #    shm_size: "2g"
  #    depends_on:
  #      - webdriver
  #    environment:
  #      <<: *selenium-nodes
  #    ports:
  #      - "7903:7900"

  webdriver:
    image: selenium/hub:4.9.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

volumes:
  postgresql:
  tdlib:
  wsmc-storage: