version: '3.8'
x-app-common: &common-variables
  POSTGRES_NAME: wsmc
  POSTGRES_USER: user
  POSTGRES_PASSWORD: 741963
  FIELD_ENCRYPTION_KEY: ${FIELD_ENCRYPTION_KEY} # Precalculated key
  WEBDRIVER_URL: 'http://webdriver:4444'
  SELENIUM_DRIVER: 'chrome'
  CELERY_BROKER_URL: 'redis://redis:6379/'
  WSMC_LOAD_AI: ${WSMC_LOAD_AI}
  NOMINATIM_USER_AGENT: 'wsmc_test_app'
  NOMINATIM_DOMAIN: 'nominatim:8080'
  NOMINATIM_SCHEME: 'http'
  DEBUG: ${DEBUG}
  TEST_VK_LOGIN: ${TEST_VK_LOGIN}
  TEST_VK_PASSWORD: ${TEST_VK_PASSWORD}
x-app-telegram: &telegram-vars
  TELEGRAM_API_ID: ${TELEGRAM_API_ID}
  TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
x-selenium-nodes: &selenium-nodes
  SE_EVENT_BUS_HOST: 'webdriver'
  SE_EVENT_BUS_PUBLISH_PORT: 4442
  SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  SE_VNC_NO_PASSWORD: 1
#  SE_SCREEN_WIDTH: 1920
#  SE_SCREEN_HEIGHT: 1080
#  SE_OPTS: "--log-level FINE"
  SE_NODE_SESSION_TIMEOUT: 800

services:
  app:
    image: indiwine/wsmc:dev
    hostname: 'app'
    ports:
      - "8000:8000"
    environment:
      <<: [ *common-variables, *telegram-vars ]
    volumes:
      - tdlib:/tmp/.tdlib_files/
      - wsmc-storage:/app/storage
    depends_on:
      - postgres
      - webdriver
      - redis
      - celery
    deploy:
      replicas: 1
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==manager"
  celery:
    image: indiwine/wsmc:dev
    hostname: 'celery'
    command: celery -A wsmc worker --concurrency=3 -n webdriver-worker@%h
    volumes:
      - wsmc-storage:/app/storage
    environment:
      <<: *common-variables
    depends_on:
      - redis
      - postgres
      - webdriver
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: '0.9'
          memory: 600M
        reservations:
          cpus: '0.25'
          memory: 200M
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  postgres:
    image: postgis/postgis:14-3.3-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "741963"
      POSTGRES_DB: "wsmc"
    volumes:
      - postgresql:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  chrome:
    image: selenium/node-chrome:113.0
    environment:
      <<: *selenium-nodes
    ports:
      - "7900"
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.9'
          memory: 3G
        reservations:
          cpus: '0.2'
          memory: 2G
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648


  webdriver:
    image: selenium/hub:4.9.1
    environment:
      SE_NODE_SESSION_TIMEOUT: 800
      SE_SESSION_REQUEST_TIMEOUT: 800
    depends_on:
      - chrome
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    deploy:
      replicas: 1

  nominatim:
    image: mediagis/nominatim:4.2
    expose:
      - "8080"
    environment:
      PBF_URL: https://download.geofabrik.de/europe/ukraine-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/ukraine-updates
      NOMINATIM_PASSWORD: very_secure_password
      IMPORT_STYLE: "admin"
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 268435456
    shm_size: 256m
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==swarm-2"

volumes:
  postgresql:
  tdlib:
  wsmc-storage:
  nominatim-data: