version: '3.8'
services:
  app:
    build: './app'
    volumes:
      - './app:/app'
      - './app/storage:/app/storage'
#  redis:
#    ports:
#      - "6379:6379"
  celery:
    build: './app'
#    command: celery -A wsmc worker -P solo
    volumes:
      - './app:/app'
  celery-common:
    build: './app'
    volumes:
      - './app:/app'
  chrome:
    ports:
      - "7900:7900"
    shm_size: 3g
    profiles:
      - "notstart"
    deploy:
      replicas: 1
  postgres:
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
  pg_exporter:
    profiles:
      - "monitoring"
  celery_exporter:
    profiles:
      - "monitoring"