version: '3.8'
services:
  app:
    build: './app'
    volumes:
      - './app:/app'
  celery:
    image: indiwine/wsmc:latest
    command: celery -A wsmc worker -P solo
    volumes:
      - './app:/app'
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data