version: '3.8'
services:
  app:
    build: './app'
    volumes:
      - './app:/app'
  celery:
    image: wsmc_app
    volumes:
      - './app:/app'
  webdriver:
    ports:
      - '4444'
  postgres:
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql: