# Generated by Django 4.1.2 on 2022-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_connection', '0002_telegrambot_alter_telegramaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='bots_to_use',
            field=models.ManyToManyField(help_text='Боти що можуть бути використані з цим аккаунтом. Переконайтись що обрані боти вже додані до цього аккаунта.', to='telegram_connection.telegrambot', verbose_name='Бот'),
        ),
    ]
