# Generated by Django 4.1.2 on 2022-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_connection', '0002_telegrambot_alter_telegramaccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='bots_to_use',
            field=models.ManyToManyField(to='telegram_connection.telegrambot'),
        ),
    ]
