global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor-swarm1:8080','cadvisor-swarm2:8080','cadvisor-swarm3:8080']