# Generated by Django 4.1.1 on 2022-10-19 16:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    replaces = [('social_media', '0001_initial'), ('social_media', '0002_location')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='Слово або фраза для пошуку', max_length=1024, verbose_name='Фраза')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фрази',
            },
        ),
        migrations.CreateModel(
            name='SmCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('social_media', models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], default='fb', max_length=4)),
            ],
            options={
                'verbose_name': 'Аккаунт соціальної мережі',
                'verbose_name_plural': 'Аккаунти соціальних мереж',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Підозрілість')),
            ],
            options={
                'verbose_name': 'Підозрюваний',
                'verbose_name_plural': 'Підозрювані',
            },
        ),
        migrations.CreateModel(
            name='SuspectSocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredential')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
            options={
                'verbose_name': 'Аккаунт підозрюваного',
                'verbose_name_plural': 'Аккаунти підозрюваних',
                'unique_together': {('credentials', 'suspect')},
            },
        ),
        migrations.CreateModel(
            name='SmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('university', models.CharField(max_length=512, null=True)),
                ('location', models.CharField(max_length=512, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredential')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
        migrations.CreateModel(
            name='SmPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_post_id', models.CharField(help_text='ID поста в соціальній мережі', max_length=25000)),
                ('social_media', models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], max_length=4)),
                ('datetime', models.DateTimeField(verbose_name='Час створення')),
                ('body', models.TextField(null=True, verbose_name='Текст')),
                ('permalink', models.URLField(help_text='Прямий лінк на пост', null=True)),
                ('raw_post', models.JSONField(editable=False, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(verbose_name='body')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.smprofile')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255)),
                ('resulting_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('result', models.JSONField()),
                ('module', models.CharField(choices=[('pk', 'Слова в постах')], max_length=2)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.screeningreport')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedPostsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('suspect_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspectsocialmediaaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='smpost',
            index=models.Index(fields=['sm_post_id', 'social_media', 'profile', 'datetime', 'suspect'], name='social_medi_sm_post_a089b0_idx'),
        ),
        migrations.AddIndex(
            model_name='smpost',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('search_vector', config='russian'), name='search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningdetail',
            index=models.Index(fields=['object_id', 'content_type', 'report', 'module'], name='social_medi_object__005848_idx'),
        ),
        migrations.AddIndex(
            model_name='collectedpostsstat',
            index=models.Index(fields=['suspect_account', 'date', 'finished'], name='social_medi_suspect_ef9e96_idx'),
        ),
        migrations.RunSQL(
            sql="\n        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE\n        ON social_media_smpost FOR EACH ROW EXECUTE FUNCTION\n        tsvector_update_trigger(search_vector, 'pg_catalog.russian', body);\n        ",
            reverse_sql='drop trigger tsvectorupdate on social_media_smposts',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Назва')),
                ('weight', models.PositiveIntegerField(default=0, help_text='Чим більша вага, тим більш підозріле місце знаходження', verbose_name='Вага')),
                ('location_data', models.JSONField(editable=False, null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Чи може бути використана ця локація для ідентифікації', verbose_name='Коректна Локація?')),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
            },
        ),
    ]
