# Generated by Django 4.1.1 on 2022-09-28 14:07

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import social_media.social_media.social_media_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='Слово або фраза для пошуку', max_length=512, verbose_name='Фраза')),
                ('wight', models.PositiveIntegerField(help_text='Чим більша вага, тим більш "підозрілою" є ця фраза', verbose_name='Вага')),
            ],
        ),
        migrations.CreateModel(
            name='SmCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('social_media', models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], default=social_media.social_media.social_media_types.SocialMediaTypes['FB'], max_length=4)),
            ],
            options={
                'verbose_name': 'Аккакунт соціальної мережі',
                'verbose_name_plural': 'Аккакунти соціальних мереж',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Підозрюваний',
                'verbose_name_plural': 'Підозрювані',
            },
        ),
        migrations.CreateModel(
            name='SuspectSocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredentials')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
            options={
                'verbose_name': 'Аккакунт підозрюванорго',
                'verbose_name_plural': 'Аккакунти підозрюваних',
                'unique_together': {('credentials', 'suspect')},
            },
        ),
    ]
