# Generated by Django 4.1.1 on 2022-10-12 15:48

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='Слово або фраза для пошуку', max_length=512, verbose_name='Фраза')),
                ('wight', models.PositiveIntegerField(help_text='Чим більша вага, тим більш "підозрілою" є ця фраза', verbose_name='Вага')),
            ],
        ),
        migrations.CreateModel(
            name='SmCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('social_media', models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], default='fb', max_length=4)),
            ],
            options={
                'verbose_name': 'Аккакунт соціальної мережі',
                'verbose_name_plural': 'Аккакунти соціальних мереж',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Підозрюваний',
                'verbose_name_plural': 'Підозрювані',
            },
        ),
        migrations.CreateModel(
            name='SuspectSocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredentials')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
            options={
                'verbose_name': 'Аккакунт підозрюванорго',
                'verbose_name_plural': 'Аккакунти підозрюваних',
                'unique_together': {('credentials', 'suspect')},
            },
        ),
        migrations.CreateModel(
            name='SmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('university', models.CharField(max_length=512, null=True)),
                ('location', models.CharField(max_length=512, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredentials')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
        ),
        migrations.CreateModel(
            name='SmPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_post_id', models.CharField(help_text='ID поста в соціальній мережі', max_length=2048)),
                ('social_media', models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], max_length=4)),
                ('datetime', models.DateTimeField()),
                ('body', models.TextField(null=True)),
                ('permalink', models.URLField(help_text='Прямий лінк на пост', null=True)),
                ('raw_post', models.JSONField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.smprofile')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedPostsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('suspect_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspectsocialmediaaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='smposts',
            index=models.Index(fields=['sm_post_id', 'social_media', 'profile', 'datetime', 'suspect'], name='social_medi_sm_post_281dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='collectedpostsstats',
            index=models.Index(fields=['suspect_account', 'date', 'finished'], name='social_medi_suspect_977422_idx'),
        ),
    ]
