# Generated by Django 4.1.1 on 2022-10-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_squashed_0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningdetail',
            name='module',
            field=models.CharField(choices=[('pk', 'Слова в постах'), ('pl', 'Місце проживання')], max_length=2),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='permalink',
            field=models.URLField(help_text='Прямий лінк на пост', max_length=2512, null=True),
        ),
    ]
