# Generated by Django 4.1.2 on 2022-10-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_alter_screeningdetail_module_alter_smpost_permalink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspect',
            options={'verbose_name': 'Людина', 'verbose_name_plural': 'Люди'},
        ),
        migrations.CreateModel(
            name='VkPostStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_offset', models.PositiveIntegerField()),
                ('suspect_social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspectsocialmediaaccount')),
            ],
        ),
    ]
