# Generated by Django 4.1.2 on 2022-11-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_alter_suspect_options_vkpoststat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningreport',
            options={'verbose_name': 'Результат перевірки', 'verbose_name_plural': 'Результати перевірок'},
        ),
    ]
