# Generated by Django 4.1.2 on 2022-11-10 14:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_suspect_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningreport',
            options={'verbose_name': 'Перевірка соцмереж', 'verbose_name_plural': 'Перевірки соцмереж'},
        ),
        migrations.AlterField(
            model_name='suspect',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='OsintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspect', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'OSINT',
            },
        ),
        migrations.CreateModel(
            name='OsintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('tg_phone_bot', 'Телефон у Telegram ботах')], max_length=50)),
                ('sub_module', models.CharField(default=None, max_length=128, null=True)),
                ('result', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.osintreport')),
            ],
        ),
    ]
