# Generated by Django 4.1.2 on 2022-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_suspect_email_alter_suspect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osintdetail',
            name='module',
            field=models.CharField(choices=[('tg_phone_bot', 'Телефон у Telegram ботах'), ('tg_email_bot', 'E-Mail у Telegram ботах'), ('tg_name_bot', "Ім'я у Telegram ботах"), ('tg_sm_bot', 'Соц. мережі у Telegram ботах'), ('holehe_email', 'HOLEHE E-Mail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ФІО'),
        ),
    ]
