# Generated by Django 4.1.2 on 2022-12-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_smprofile_oid_alter_smprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smprofile',
            name='home_town',
            field=models.CharField(max_length=512, null=True, verbose_name='Місце народження'),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='credentials',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredential'),
        ),
    ]
