# Generated by Django 4.1.7 on 2023-02-22 07:28

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0011_smprofile_home_town_alter_smprofile_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectedpostsstat',
            options={'verbose_name': 'Статистика ФБ', 'verbose_name_plural': 'Статистика ФБ'},
        ),
        migrations.AlterModelOptions(
            name='osintdetail',
            options={'verbose_name': 'OSINT Деталі', 'verbose_name_plural': 'OSINT Деталі'},
        ),
        migrations.AlterModelOptions(
            name='screeningdetail',
            options={'verbose_name': 'Деталі перевірки соцмереж', 'verbose_name_plural': 'Деталі перевірки соцмереж'},
        ),
        migrations.AlterModelOptions(
            name='vkpoststat',
            options={'verbose_name': 'Статистика ВК', 'verbose_name_plural': 'Статистика ВК'},
        ),
        migrations.AlterField(
            model_name='screeningdetail',
            name='module',
            field=models.CharField(choices=[('pk', 'Слова в постах'), ('pl', 'Місце проживання'), ('ci', 'Конфіденційна інформація')], max_length=2, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='screeningdetail',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID сутності'),
        ),
        migrations.AlterField(
            model_name='screeningreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='screeningreport',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='screeningreport',
            name='resulting_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Підозрілість'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='datetime',
            field=models.DateTimeField(help_text='Час коли пост було створено в соціальній мережі', verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='permalink',
            field=models.URLField(editable=False, help_text='Прямий лінк на пост', max_length=2512, null=True),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='profile',
            field=models.ForeignKey(help_text="Профіль зв'язаний з цим постом", on_delete=django.db.models.deletion.CASCADE, to='social_media.smprofile', verbose_name='Профіль'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='sm_post_id',
            field=models.CharField(editable=False, help_text='ID поста в соціальній мережі', max_length=25000, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='social_media',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], max_length=4, verbose_name='Соціальна мережа'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect', verbose_name='Людина'),
        ),
        migrations.CreateModel(
            name='SmPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(editable=False, max_length=2512)),
                ('url', models.URLField(editable=False, null=True)),
                ('permalink', models.URLField(editable=False, null=True)),
                ('image', models.ImageField(default=None, editable=False, null=True, upload_to='post_images')),
                ('prediction', models.JSONField(default=None, editable=False, null=True)),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='social_media.smpost')),
            ],
        ),
        migrations.AddIndex(
            model_name='smpostimage',
            index=models.Index(fields=['post', 'oid', 'prediction'], name='social_medi_post_id_5f6a63_idx'),
        ),
    ]
