# Generated by Django 4.1.7 on 2023-04-24 13:00

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def append_origin_to_posts(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    posts_model = apps.get_model('social_media', 'smpost')
    profile_model = apps.get_model('social_media', 'smprofile')
    content_type_model = apps.get_model('contenttypes', 'contenttype')
    suspect_social_media_model = apps.get_model('social_media', 'suspectsocialmediaaccount')

    content_type_item = content_type_model.objects.get_for_model(posts_model)

    for profile in profile_model.objects.all().iterator():
        profile.suspect_social_media = suspect_social_media_model.objects.get(
            suspect=profile.suspect,
            credentials=profile.credentials
        )
        profile.save()

    for post in posts_model.objects.all().iterator():
        post.origin_type = content_type_item
        post.origin_id = post.profile_id
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_media', '0012_alter_collectedpostsstat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Час коли пост було створено в соціальній мережі',
                                                  verbose_name='Час створення')),
                ('body', models.TextField(null=True, verbose_name='Текст')),
                ('oid', models.CharField(editable=False, help_text='ID поста в соціальній мережі', max_length=25000,
                                         verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.URLField()),
                ('oid', models.CharField(max_length=25000)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SmLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField(verbose_name='ID сутності')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='smpost',
            name='social_medi_sm_post_a089b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_suspect_1292a5_idx',
        ),
        migrations.AddField(
            model_name='smpost',
            name='origin_id',
            field=models.PositiveIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='smpost',
            name='origin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='suspect_social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='social_media.suspectsocialmediaaccount'),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='was_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='screeningdetail',
            name='module',
            field=models.CharField(
                choices=[('pk', 'Слова в постах'), ('pl', 'Місце проживання'), ('ci', 'Конфіденційна інформація'),
                         ('sy', 'Символи')], max_length=2, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='smpostimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='smpostimage',
            name='permalink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='smpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.smpost'),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='suspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.suspect'),
        ),
        migrations.AddIndex(
            model_name='smpost',
            index=models.Index(
                fields=['sm_post_id', 'social_media', 'profile', 'datetime', 'suspect', 'origin_type', 'origin_id'],
                name='social_medi_sm_post_f3cc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['credentials', 'oid', 'was_collected'], name='social_medi_credent_ca74c7_idx'),
        ),
        migrations.AddField(
            model_name='smlikes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.smprofile'),
        ),
        migrations.AddField(
            model_name='smlikes',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='smgroup',
            name='credentials',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT,
                                    to='social_media.smcredential'),
        ),
        migrations.AddField(
            model_name='smgroup',
            name='suspect_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='social_media.suspectgroup'),
        ),
        migrations.AddField(
            model_name='smcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.smprofile'),
        ),
        migrations.AddField(
            model_name='smcomment',
            name='parent_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='social_media.smcomment'),
        ),
        migrations.AddField(
            model_name='smcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.smpost'),
        ),
        migrations.AlterUniqueTogether(
            name='smlikes',
            unique_together={('owner', 'parent_type', 'parent_id')},
        ),
        migrations.AddIndex(
            model_name='smgroup',
            index=models.Index(fields=['suspect_group', 'oid', 'credentials'], name='social_medi_suspect_920fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='smcomment',
            index=models.Index(fields=['owner', 'oid', 'parent_comment', 'post'],
                               name='social_medi_owner_i_e6af8b_idx'),
        ),
        migrations.RunPython(append_origin_to_posts),
        migrations.RemoveField(model_name='smpost', name='suspect'),
        migrations.RemoveField(model_name='smprofile', name='suspect'),
        migrations.AlterField(
            model_name='smpost',
            name='origin_id',
            field=models.PositiveIntegerField(null=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='origin_type',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.contenttype'),
        )
    ]
