# Generated by Django 4.1.7 on 2023-04-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0013_smcomment_smgroup_smlikes_suspectgroup_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smpost',
            name='social_medi_sm_post_f3cc3b_idx',
        ),
        migrations.AddField(
            model_name='suspectgroup',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='social_media.smcredential'),
        ),
        migrations.AddIndex(
            model_name='smpost',
            index=models.Index(fields=['sm_post_id', 'social_media', 'profile', 'datetime', 'origin_type', 'origin_id'], name='social_medi_sm_post_59156e_idx'),
        ),
    ]
