# Generated by Django 4.1.7 on 2023-04-27 07:16

import django.db.models.deletion
from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

def append_additional_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    sm_group_model = apps.get_model('social_media', 'smgroup')
    sm_post_model = apps.get_model('social_media', 'smpost')
    sm_profile_model = apps.get_model('social_media', 'smprofile')
    content_type_model = apps.get_model('contenttypes', 'contenttype')

    content_type_smprofile_item = content_type_model.objects.get_for_model(sm_profile_model)

    for profile in sm_profile_model.objects.all():
        if not profile.oid:
            # sm_post_model.objects.filter(profile=profile).delete()
            profile.delete()
            continue

        profile.social_media = profile.credentials.social_media
        profile.save()

    for group in sm_group_model.objects.all().iterator():
        group.social_media = group.credentials.social_media
        group.save()

    for post in sm_post_model.objects.all().iterator():
        post.author_type = content_type_smprofile_item
        post.author_id = post.profile_id
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('social_media', '0015_remove_smgroup_social_medi_suspect_920fbf_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(append_additional_data),
    ]
