# Generated by Django 4.1.7 on 2023-04-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_media', '0016_auto_20230427_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smgroup',
            name='social_media',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')],
                                   max_length=4, verbose_name='Соціальна мережа'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='author_id',
            field=models.PositiveIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author',
                                    to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='social_media',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')],
                                   max_length=4, verbose_name='Соціальна мережа'),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='oid',
            field=models.CharField(help_text='ID користувача в соціальній мережі', max_length=512,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smgroup',
            name='social_media',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')],
                                   max_length=4, verbose_name='Соціальна мережа'),
        ),
    ]
