# Generated by Django 4.2.1 on 2023-05-10 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0020_location_pol'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_credent_e27885_idx',
        ),
        migrations.AddField(
            model_name='smprofile',
            name='location_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='location_precise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['credentials', 'oid', 'was_collected', 'suspect_social_media', 'social_media', 'location_known', 'location_precise'], name='social_medi_credent_bdf79b_idx'),
        ),
    ]
