# Generated by Django 4.2.1 on 2023-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0021_remove_smprofile_social_medi_credent_e27885_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmProfileLocationFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('locations', models.ManyToManyField(to='social_media.location')),
            ],
        ),
    ]
