# Generated by Django 4.2.1 on 2023-05-12 07:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0022_smprofilelocationfilter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_credent_bdf79b_idx',
        ),
        migrations.AddField(
            model_name='smprofile',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='pol',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['credentials', 'oid', 'was_collected', 'suspect_social_media', 'social_media', 'location_known', 'location_precise', 'is_reviewed'], name='social_medi_credent_f464d8_idx'),
        ),
    ]
