# Generated by Django 4.2.1 on 2023-06-20 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0024_fix_html_encoding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_credent_f464d8_idx',
        ),
        migrations.AddField(
            model_name='smprofile',
            name='comment',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='person_responsible',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='screening_status',
            field=models.CharField(choices=[('pe', 'В очікуванні'), ('re', 'Русня'), ('ok', 'Норм')], default='pe', max_length=4),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='location_known',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='location_precise',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='suspect_social_media',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media.suspectsocialmediaaccount'),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['credentials', 'oid', 'was_collected', 'suspect_social_media', 'social_media', 'location_known', 'location_precise', 'is_reviewed', 'screening_status', 'person_responsible'], name='social_medi_credent_b7cfc0_idx'),
        ),
    ]
