# Generated by Django 4.2.1 on 2023-07-05 11:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0025_remove_smprofile_social_medi_credent_f464d8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smpost',
            name='social_medi_sm_post_cb0c67_idx',
        ),
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_credent_b7cfc0_idx',
        ),
        migrations.AddField(
            model_name='smpost',
            name='screening_status',
            field=models.CharField(blank=True, choices=[('pe', 'В очікуванні'), ('re', 'Русня'), ('ok', 'Норм')], default='pe', max_length=4),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='authenticity_status',
            field=models.CharField(blank=True, choices=[('hn', 'Людина'), ('bt', 'Бот'), ('un', 'Невідомо')], default='un', max_length=4),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='person_responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='screening_status',
            field=models.CharField(blank=True, choices=[('pe', 'В очікуванні'), ('re', 'Русня'), ('ok', 'Норм')], default='pe', max_length=4),
        ),
        migrations.AddIndex(
            model_name='smpost',
            index=models.Index(fields=['sm_post_id', 'social_media', 'datetime', 'origin_type', 'origin_id', 'author_type', 'author_id', 'screening_status'], name='social_medi_sm_post_514524_idx'),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['credentials', 'oid', 'was_collected', 'suspect_social_media', 'social_media', 'location_known', 'location_precise', 'is_reviewed', 'screening_status', 'person_responsible', 'authenticity_status'], name='social_medi_credent_a52618_idx'),
        ),
    ]
