# Generated by Django 4.2.4 on 2023-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0027_remove_suspectgroup_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smcredential',
            name='session',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
    ]
