# Generated by Django 4.2.4 on 2023-09-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0028_smcredential_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkPostStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_offset', models.PositiveIntegerField()),
                ('last_anchor', models.CharField(max_length=512)),
                ('suspect_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.suspectgroup')),
                ('suspect_social_media', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.suspectsocialmediaaccount')),
            ],
            options={
                'verbose_name': 'Статистика ОК',
                'verbose_name_plural': 'Статистика ОК',
            },
        ),
    ]
