# Generated by Django 4.2.4 on 2023-09-28 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0029_okpoststat'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_credent_a52618_idx',
        ),
        migrations.RemoveField(
            model_name='smprofile',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='smprofile',
            name='in_junk',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='screening_status',
            field=models.CharField(choices=[('pe', 'В очікуванні'), ('re', 'Ждун'), ('ok', 'Норм'), ('ld', 'БОМБАС'), ('nr', 'Росія')], default='pe', max_length=4),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='smprofile',
            name='screening_status',
            field=models.CharField(choices=[('pe', 'В очікуванні'), ('re', 'Ждун'), ('ok', 'Норм'), ('ld', 'БОМБАС'), ('nr', 'Росія')], default='pe', max_length=4),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['oid', 'was_collected', 'social_media', 'in_junk', 'screening_status', 'person_responsible', 'authenticity_status'], name='social_medi_oid_0920d4_idx'),
        ),
    ]
