# Generated by Django 4.2.4 on 2023-09-29 08:17
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_media', '0030_remove_smprofile_social_medi_credent_a52618_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_oid_0920d4_idx',
        ),
        migrations.AddField(
            model_name='smprofile',
            name='country_ref',
            field=models.ForeignKey(default=None, editable=False, null=True,
                                    on_delete=django.db.models.deletion.RESTRICT, to='social_media.country'),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(
                fields=['oid', 'was_collected', 'social_media', 'in_junk', 'screening_status', 'person_responsible',
                        'authenticity_status', 'country_ref'], name='social_medi_oid_2579fa_idx'),
        ),

    ]
