# Generated by Django 4.2.4 on 2023-09-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0033_remove_smprofile_country'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_oid_2579fa_idx',
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(fields=['oid', 'was_collected', 'social_media', 'in_junk', 'screening_status', 'authenticity_status'], name='social_medi_oid_ad7690_idx'),
        ),
    ]
