# Generated by Django 4.2.4 on 2023-10-04 13:31

from django.db import migrations
from django.db.models import Q

from social_media.common import print_progress_bar
from social_media.models import SmProfile, Country, SmLikes, SmPost


def move_to_junk(apps, schema_editor):
    sm_profile: SmProfile = apps.get_model('social_media', 'smprofile')
    content_type_model = apps.get_model('contenttypes', 'contenttype')
    country: Country = apps.get_model('social_media', 'country')
    sm_likes: SmLikes = apps.get_model('social_media', 'smlikes')
    sm_post: SmPost = apps.get_model('social_media', 'smpost')
    profile_content_type = content_type_model.objects.get_for_model(sm_profile)


    counties_to_remove = country.objects.filter(~Q(code='ua'))

    total = sm_profile.objects.filter(Q(country_ref__in=counties_to_remove) | Q(location_known=False)).count()
    count = 0

    for profile in sm_profile.objects.filter(Q(country_ref__in=counties_to_remove) |
                                             Q(location_known=False)
                                             ).iterator():
        count += 1
        print_progress_bar(count, total, prefix='Progress:', suffix='Complete', length=50)

        sm_likes.objects.filter(owner=profile).delete()
        sm_post.objects.filter(
            Q(author_type=profile_content_type, author_id=profile.pk) |
            Q(origin_type=profile_content_type, origin_id=profile.pk)
        ).delete()
        sm_profile.objects.filter(pk=profile.pk).update(in_junk=True)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('social_media', '0034_remove_smprofile_social_medi_oid_2579fa_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(move_to_junk)
    ]
