# Generated by Django 4.2.4 on 2023-10-10 11:51

import django.db.models.deletion
from django.db import migrations, models

import social_media.models.suspectgroup
from social_media.social_media import SocialMediaTypes


def apply_sm_type(apps, schema_editor):
    suspect_groups = apps.get_model('social_media', 'SuspectGroup')
    for group in suspect_groups.objects.all():
        group.sm_type = SocialMediaTypes.from_url(group.url)
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('social_media', '0035_move_to_junk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Місто (російською)')),
                ('place_collected', models.BooleanField(default=False, verbose_name='Місце зібрано')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='smprofile',
            name='social_medi_oid_ad7690_idx',
        ),
        migrations.AddField(
            model_name='smprofile',
            name='is_wall_available',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='smprofile',
            name='posts_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suspectgroup',
            name='has_been_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suspectgroup',
            name='sm_type',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')],
                                   default=None, max_length=4, verbose_name='Соціальна мережа', null=True),
        ),
        migrations.AlterField(
            model_name='suspectgroup',
            name='url',
            field=models.URLField(unique=True, validators=[social_media.models.suspectgroup.validate_social_media_url]),
        ),
        migrations.AddIndex(
            model_name='smprofile',
            index=models.Index(
                fields=['oid', 'was_collected', 'social_media', 'in_junk', 'screening_status', 'authenticity_status',
                        'posts_collected'], name='social_medi_oid_2aa9e1_idx'),
        ),
        migrations.AddField(
            model_name='suspectplace',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='social_media.country'),
        ),
        migrations.AddField(
            model_name='okpoststat',
            name='suspect_place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='social_media.suspectplace'),
        ),
        migrations.RunPython(code=apply_sm_type, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='suspectgroup',
            name='sm_type',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')],
                                   max_length=4, verbose_name='Соціальна мережа'),
        ),
    ]
