# Generated by Django 4.2.4 on 2023-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0036_suspectplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smgroup',
            name='posts_collected',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='suspectgroup',
            name='sm_type',
            field=models.CharField(choices=[('fb', 'Facebook'), ('vk', 'Вконтакте'), ('ok', 'Однокласники')], default=None, max_length=4, verbose_name='Соціальна мережа'),
        ),
    ]
